"""The vendored koine schemas are pinned byte-for-byte to the koine sibling checkout.

The trainer ships a copy of ``finetune-job.schema.json`` (+ the two schemas it refs) so a
deployed service validates jobs without a ``../koine`` beside it (ADR-0001). That copy is a
snapshot, and a snapshot drifts: this test byte-compares each vendored file against koine's
canonical ``schemas/`` — the same discipline the TS side keeps for the koine registry fixture
(``schemas/src/koine-fixture-drift.test.ts``). A ``koine:*`` bump that advanced the schema is
red here until the copy is refreshed (recopy from koine, never hand-edit).

koine is a sibling of the agora working tree (``../koine``); resolved against both this tree's
own root and — for a git worktree, whose ``../koine`` does not exist — the primary working tree
via git's common dir. An absent koine skips (a standalone agora checkout), never silently
passes as green.
"""

from __future__ import annotations

import subprocess
from pathlib import Path

import pytest

from agora_trainer.schemas import SCHEMA_FILES

VENDORED_DIR = Path(__file__).resolve().parents[1] / "src" / "agora_trainer" / "schemas"


def _koine_schemas_dir() -> Path | None:
    repo_root = Path(__file__).resolve().parents[2]
    roots = [repo_root]
    try:
        common = subprocess.run(
            ["git", "rev-parse", "--path-format=absolute", "--git-common-dir"],
            cwd=repo_root,
            capture_output=True,
            text=True,
            check=True,
        ).stdout.strip()
        if common:
            roots.append(Path(common).parent)  # the primary working tree's root
    except (OSError, subprocess.CalledProcessError):
        pass  # git unavailable — the relative candidate is all we can try
    for root in roots:
        candidate = root.parent / "koine" / "schemas"
        if (candidate / "finetune-job.schema.json").exists():
            return candidate
    return None


KOINE_DIR = _koine_schemas_dir()


@pytest.mark.skipif(
    KOINE_DIR is None,
    reason="standalone checkout: the koine sibling (../koine/schemas) is absent",
)
@pytest.mark.parametrize("name", SCHEMA_FILES)
def test_vendored_schema_is_byte_identical_to_koine(name: str) -> None:
    assert KOINE_DIR is not None  # narrowed for the type checker; skipif guards the None case
    vendored = (VENDORED_DIR / name).read_bytes()
    canonical = (KOINE_DIR / name).read_bytes()
    assert vendored == canonical, (
        f"{name} has drifted from koine; refresh it (do not hand-edit):\n"
        f"  cp {KOINE_DIR / name} {VENDORED_DIR / name}"
    )


#: The OTHER vendored copy in this repo — what both artifact validators read
#: (``schemas/src/koine-schemas/``, regenerated by ``regen-koine-schemas.mjs``). It sits inside
#: this checkout, so unlike the koine pin above this comparison never skips: a refresh applied to
#: one copy and not the other is red in a standalone agora clone too. Its mirror image is
#: ``schemas/src/koine-schema-drift.test.ts``, which asserts the same bytes from the TS side.
SNAPSHOT_DIR = Path(__file__).resolve().parents[2] / "schemas" / "src" / "koine-schemas"


@pytest.mark.parametrize("name", SCHEMA_FILES)
def test_vendored_schema_matches_the_ts_snapshot(name: str) -> None:
    """The trainer's copy and the validators' snapshot are the same bytes — never a fork.

    Both are snapshots of the same koine file, so a divergence means one was refreshed (or
    hand-edited) without the other, leaving the trainer admitting jobs the conformance
    validators reject. Refresh BOTH from koine; never hand-edit either.
    """
    vendored = (VENDORED_DIR / name).read_bytes()
    snapshot = (SNAPSHOT_DIR / name).read_bytes()
    assert vendored == snapshot, (
        f"{name} has forked between the trainer's vendored copy and the validators' snapshot:\n"
        f"  {VENDORED_DIR / name}\n"
        f"  {SNAPSHOT_DIR / name}\n"
        "refresh both from koine (npm run -w @agora/schemas regen:koine-schemas, then recopy)"
    )
